// Live smoke test against a real ManageSieve account. Reads creds via
// the rustymail::managesieve credential resolver (accounts.json with
// optional sieve override; otherwise falls back to imap host + 4190 +
// imap user/pass + STARTTLS).
//
// Usage:
//   cargo run --example sieve_smoke -- probe
//   cargo run --example sieve_smoke -- install
//   cargo run --example sieve_smoke -- uninstall
//
// `probe` is read-only: it lists scripts and prints capabilities.
// `install` uploads `rustymail-github-filter` and activates it.
// `uninstall` deactivates and deletes the same script.

use std::process::ExitCode;
use std::time::Duration;

use rustymail::managesieve::{
    connect_starttls, resolve_for_account, Error, SieveClient,
};
use tokio_native_tls::TlsStream;
use tokio::net::TcpStream;

const SCRIPT_NAME: &str = "rustymail-github-filter";
const MASTER_NAME: &str = "rustymail-master";
const OX_NAME: &str = "Open-Xchange";

const SCRIPT_BODY: &str = "\
require [\"fileinto\", \"mailbox\", \"envelope\"];

# Created by rustymail sieve_smoke example.
# Files everything from any @github.com sender into the \"GitHub\"
# folder; creates the folder if it doesn't exist.
if envelope :domain \"from\" \"github.com\" {
    fileinto :create \"GitHub\";
}
";

/// Master script that runs the existing Open-Xchange categorization
/// AND our github-filter. mailbox.org's OX bundle regenerates
/// Open-Xchange when the user touches the web-UI filter editor, so we
/// don't replace it — we delegate to it via :personal include and add
/// our own logic alongside.
const MASTER_BODY_TMPL: &str = "\
require [\"include\"];

# Generated by rustymail. Activates both the OX-managed categorization
# script and the rustymail-managed sieve scripts as a coherent set.
include :personal \"Open-Xchange\";
include :personal \"rustymail-github-filter\";
";

#[tokio::main(flavor = "current_thread")]
async fn main() -> ExitCode {
    let mode = std::env::args().nth(1).unwrap_or_else(|| "probe".into());
    let accounts_path = std::env::var("RUSTYMAIL_ACCOUNTS_PATH")
        .unwrap_or_else(|_| "config/accounts.json".to_string());
    let account_id = std::env::var("RUSTYMAIL_SIEVE_ACCOUNT").ok();

    let creds = match resolve_for_account(&accounts_path, account_id.as_deref()) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("FAIL: resolve credentials: {e}");
            return ExitCode::from(2);
        }
    };
    println!(
        "creds: host={} port={} user={} starttls={}",
        creds.host, creds.port, creds.username, creds.use_starttls,
    );

    let mut client: SieveClient<TlsStream<TcpStream>> =
        match connect_starttls(&creds.host, creds.port, Duration::from_secs(15)).await {
            Ok(c) => c,
            Err(e) => {
                eprintln!("FAIL: connect_starttls: {e}");
                return ExitCode::from(3);
            }
        };
    println!("connected + STARTTLS upgraded");

    if let Err(e) = client.authenticate_plain(&creds.username, &creds.password).await {
        eprintln!("FAIL: authenticate_plain: {e}");
        return ExitCode::from(4);
    }
    println!("authenticated as {}", creds.username);

    let outcome = match mode.as_str() {
        "probe" => probe(&mut client).await,
        "install" => install(&mut client).await,
        "uninstall" => uninstall(&mut client).await,
        other => {
            eprintln!("unknown mode {other:?}; valid: probe, install, uninstall");
            Err(Error::Protocol("bad CLI arg".into()))
        }
    };

    let _ = client.logout().await; // best-effort

    match outcome {
        Ok(()) => {
            println!("OK");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("FAIL: {e}");
            ExitCode::from(5)
        }
    }
}

async fn probe<S>(client: &mut SieveClient<S>) -> Result<(), Error>
where
    S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    let caps = client.capability().await?;
    println!("\nserver capabilities:");
    println!("  implementation = {:?}", caps.implementation);
    println!("  version        = {:?}", caps.version);
    println!("  sieve ext      = {:?}", caps.sieve_extensions);
    println!("  sasl           = {:?}", caps.sasl_mechanisms);
    println!("  notify         = {:?}", caps.notify_methods);
    println!("  max_redirects  = {:?}", caps.max_redirects);

    let scripts = client.list_scripts().await?;
    println!("\nscripts on server ({}):", scripts.len());
    for (name, active) in &scripts {
        println!("  {} {name}", if *active { "*" } else { " " });
    }
    if scripts.is_empty() {
        println!("  (none)");
    }
    Ok(())
}

async fn install<S>(client: &mut SieveClient<S>) -> Result<(), Error>
where
    S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    let scripts = client.list_scripts().await?;
    let has_ox = scripts.iter().any(|(n, _)| n == OX_NAME);

    println!("\nchecking github-filter body...");
    client.check_script(SCRIPT_BODY).await?;
    println!("  ok");

    println!("uploading {SCRIPT_NAME}...");
    client.put_script(SCRIPT_NAME, SCRIPT_BODY).await?;
    println!("  ok");

    if has_ox {
        println!("Open-Xchange present; building master script that includes both...");
        let _ = MASTER_BODY_TMPL; // Placeholder — body is constant below.
        client.check_script(MASTER_BODY_TMPL).await?;
        client.put_script(MASTER_NAME, MASTER_BODY_TMPL).await?;
        println!("  uploaded {MASTER_NAME}");
        client.set_active(MASTER_NAME).await?;
        println!("  activated {MASTER_NAME} (preserves Open-Xchange categorization)");
    } else {
        println!("Open-Xchange not present; activating {SCRIPT_NAME} directly");
        client.set_active(SCRIPT_NAME).await?;
    }

    println!("\nfinal script state:");
    for (name, active) in client.list_scripts().await? {
        println!("  {} {name}", if active { "*" } else { " " });
    }
    Ok(())
}

async fn uninstall<S>(client: &mut SieveClient<S>) -> Result<(), Error>
where
    S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    let scripts = client.list_scripts().await?;
    let active = scripts.iter().find(|(_, a)| *a).map(|(n, _)| n.clone());
    let has_master = scripts.iter().any(|(n, _)| n == MASTER_NAME);
    let has_filter = scripts.iter().any(|(n, _)| n == SCRIPT_NAME);
    let has_ox = scripts.iter().any(|(n, _)| n == OX_NAME);

    // If our master is active, hand activation back to Open-Xchange (or
    // nothing if OX isn't there) before we delete anything.
    if active.as_deref() == Some(MASTER_NAME) {
        if has_ox {
            println!("re-activating {OX_NAME} so categorization survives the cleanup...");
            client.set_active(OX_NAME).await?;
        } else {
            println!("deactivating master (no OX to fall back to)");
            client.deactivate().await?;
        }
    } else if active.as_deref() == Some(SCRIPT_NAME) {
        client.deactivate().await?;
    }

    if has_master {
        println!("deleting {MASTER_NAME}...");
        client.delete_script(MASTER_NAME).await?;
    }
    if has_filter {
        println!("deleting {SCRIPT_NAME}...");
        client.delete_script(SCRIPT_NAME).await?;
    }
    if !has_master && !has_filter {
        println!("nothing to clean up; rustymail-managed scripts not present");
    }

    println!("\nfinal script state:");
    for (name, active) in client.list_scripts().await? {
        println!("  {} {name}", if active { "*" } else { " " });
    }
    Ok(())
}
